-- Zabbix webhook 告警独立入库（不写 tb_alert_record）

CREATE TABLE IF NOT EXISTS `tb_zabbix_alert_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` varchar(64) NOT NULL,
  `trigger_id` varchar(64) DEFAULT NULL,
  `host_id` varchar(64) DEFAULT NULL,
  `host_host` varchar(128) DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `host_ip` varchar(64) DEFAULT NULL,
  `host_group` varchar(255) DEFAULT NULL,
  `severity_code` varchar(16) DEFAULT NULL,
  `severity_name` varchar(32) DEFAULT NULL,
  `trigger_name` varchar(500) DEFAULT NULL,
  `trigger_key` varchar(255) DEFAULT NULL,
  `trigger_value` varchar(16) DEFAULT NULL,
  `item_id` varchar(64) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `item_value` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `event_time` datetime DEFAULT NULL,
  `first_event_time` datetime DEFAULT NULL,
  `last_event_time` datetime DEFAULT NULL,
  `resolved_time` datetime DEFAULT NULL,
  `event_duration` varchar(64) DEFAULT NULL,
  `duration_sec` bigint DEFAULT NULL,
  `webhook_log_id` bigint DEFAULT NULL,
  `raw_json` longtext,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_id` (`event_id`),
  KEY `idx_status` (`status`),
  KEY `idx_event_time` (`event_time`),
  KEY `idx_host_ip` (`host_ip`),
  KEY `idx_trigger_id` (`trigger_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_zabbix_alert_event_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` varchar(64) NOT NULL,
  `trigger_id` varchar(64) DEFAULT NULL,
  `host_id` varchar(64) DEFAULT NULL,
  `host_host` varchar(128) DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `host_ip` varchar(64) DEFAULT NULL,
  `host_group` varchar(255) DEFAULT NULL,
  `severity_code` varchar(16) DEFAULT NULL,
  `severity_name` varchar(32) DEFAULT NULL,
  `trigger_name` varchar(500) DEFAULT NULL,
  `trigger_key` varchar(255) DEFAULT NULL,
  `trigger_value` varchar(16) DEFAULT NULL,
  `item_id` varchar(64) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `item_value` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `event_time` datetime DEFAULT NULL,
  `event_duration` varchar(64) DEFAULT NULL,
  `duration_sec` bigint DEFAULT NULL,
  `webhook_log_id` bigint DEFAULT NULL,
  `payload_json` longtext,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_status_time` (`event_id`,`status`,`event_time`),
  KEY `idx_his_event_time` (`event_time`),
  KEY `idx_his_host_ip` (`host_ip`),
  KEY `idx_his_trigger_id` (`trigger_id`),
  KEY `idx_his_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_zabbix_alert_ai_report` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `period_type` varchar(20) NOT NULL,
  `period_start` datetime NOT NULL,
  `period_end` datetime NOT NULL,
  `model_name` varchar(100) DEFAULT NULL,
  `report_status` tinyint NOT NULL COMMENT '1成功 2失败',
  `summary` varchar(500) DEFAULT NULL,
  `input_json` longtext,
  `report_json` longtext,
  `report_markdown` longtext,
  `error_message` text,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_period` (`period_type`,`period_start`,`period_end`),
  KEY `idx_create_date` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
